version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/test1234
    ports:
      - "7474:7474"
      - "7687:7687"

  fastapi:
    build: ./fastapi
    depends_on:
      - postgres
      - neo4j
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
      POSTGRES_HOST: postgres
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test1234
      OLLAMA_URL: http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
